# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in tv_shows.gemspec
gemspec

gem "rake", "~> 13.0"

gem 'nokogiri'
gem 'open-uri'
gem 'pry'
gem 'BCrypt'
